### ISSUE TITLE
[TypeError: tuple indices must be integers or slices, not tuple] from post_process_data.py

### ISSUE THREAD

**Issue by LemingVan** [jessecusack/DIMES_eddy_wave_interactions#1]
When I run `python post_process_data.py` following the guidance, I got the error :

![2021-06-19 173146](https://user-images.githubusercontent.com/46369483/123093229-06bd0f80-d45e-11eb-9630-1ba601a88932.png)
 
Then I changed the `reduce(np.average, weights=sig.hann(nperseg))` to `reduce(np.average)` at `line 721, 726, 731, 736, 741, 746, 751, 756, 762, 768`. The code works now.

But I'm not sure if this is the right way to handle it, can anyone answer this?

**Comment by jessecusack** [comment]
Hey @LemingVan sorry it has taken me so long to look into this, I away for fieldwork. I'm glad to see you found a solution, although I not 100% sure on the xarray API for the reduce function, so I don't know if it is doing exactly the same thing. 

I'll see if I get the same error on my machine.

**Comment by jessecusack** [comment]
So I got the same error as you with a fresh conda environment. There must have been some breaking changes to xarray since I created this repository. My solution is to install an older version of xarray (e.g. run `conda install xarray=0.16`) and then it ran no problem on my machine.
